### PR TITLE
Added a .travis.yml file.

### LINKED ISSUE #26: Add a .travis.yml file with Node environment
Otherwise Travis tries to use "standard configuration" (Ruby) and fails.

### PR DESCRIPTION
**Pull request by StuntsPT**
As per the title.
Fixes #26 .

### CODE REVIEW

**Comment by StuntsPT** [comment]
The tests now run, but one of them seems to be failing.

**Comment by thejmazz** [comment]
Awesome thanks, I'll take a look at the failing test soon. If you add me as reviewer I can merge this

**Comment by StuntsPT** [comment]
Thanks @thejmazz .
I've added you as a reviewer so you can perform the merge.
Cheers!

**Comment by bmpvieira** [comment]
Should we move this to the Backlog or is it an easy fix?

**Review by thejmazz — APPROVED** [review]

**Pull request merged**
